#!/bin/bash

# Remove the version of notebooks stored in the repo version we use to build the Binder
# image
rm -rf ~/content
# Download latest notebooks from LADAL
svn export https://github.com/SLCLADAL/interactive-notebooks/trunk/notebooks ~/notebooks
# Create a backup copy, if the user needs originals
cp -r ~/notebooks ~/originals

# This line is required according to Binder manual
exec "$@"
